#pragma once
//GHOUL
#define GHOUL_BBOX_WIDTH     16
#define GHOUL_BBOX_HEIGHT    31
#define GHOUL_WALKING_SPEED  0.052f
//SKELETON
#define SKELETON_BBOX_WIDTH   16
#define SKELETON_BBOX_HEIGHT  32
#define SKELETON_STATE_JUMP	  1
#define SKELETON_STATE_ATTACK 2
//FLEAMAN
#define FLEAMAN_BBOX_WIDTH	    16
#define FLEAMAN_BBOX_HEIGHT	    16
#define FLEAMAN_GRAVITY		    0.00042f
#define FLEAMAN_JUMP_SPEED_X	0.09f
#define FLEAMAN_STATE_READY	    0
#define FLEAMAN_STATE_JUMP      1
//GHOST
#define GHOST_BBOX_WIDTH  16
#define GHOST_BBOX_HEIGHT 16

//ID SUBWEAPON
#define ID_DAGGER	    40003
#define ID_BOOMERANG	40004
#define ID_HOLYWATER	40019
#define ID_AXE	        40020
#define ID_WATCH	    40021

//SCREEN
#define SCREEN_WIDTH	270
#define SCREEN_HEIGHT   270
//OBJECT TYPE
#define OBJECT_TYPE_SIMON			 0
#define OBJECT_TYPE_BRICK			 1	 
#define OBJECT_TYPE_TORCH			 2	 
#define OBJECT_TYPE_WHIP			 3	 
#define OBJECT_TYPE_ITEM_HEART		 4	 
#define OBJECT_TYPE_ITEM_CHAIN		 5	 
#define OBJECT_TYPE_ITEM_DAGGER		 6	 
#define OBJECT_TYPE_DAGGER			 7	 
#define OBJECT_TYPE_KNIGHT		     8 
#define OBJECT_TYPE_BOTSTAIR	     9
#define OBJECT_TYPE_TOPSTAIR 	     10
#define OBJECT_TYPE_ITEM_BOOMERANG	 11
#define OBJECT_TYPE_BOOMERANG		 12	
#define OBJECT_TYPE_BREAKABLE_BRICK	 13
#define OBJECT_TYPE_CROWN_ITEM	     14
#define	OBJECT_TYPE_ROCKS	         15
#define OBJECT_TYPE_BAT	             16
#define OBJECT_TYPE_MOVING_PFLATFORM 17
#define OBJECT_TYPE_ITEM_SMALL_HEART 18
#define OBJECT_TYPE_ITEM_MONEY_BAG   19
#define OBJECT_TYPE_ITEM_HOLYWATER   20
#define OBJECT_TYPE_ITEM_AXE         21
#define OBJECT_TYPE_ITEM_WATCH       22
#define OBJECT_TYPE_HOLYWATER		 23
#define OBJECT_TYPE_AXE	             24
#define OBJECT_TYPE_GHOUL	         25
#define OBJECT_TYPE_BOSS	         26
#define OBJECT_TYPE_GHOST	         27
#define OBJECT_TYPE_FLEAMAN	         28
#define OBJECT_TYPE_RAVEN	         29
#define OBJECT_TYPE_SKELETON	     30
#define OBJECT_TYPE_BONE			 31
#define OBJECT_TYPE_EFFECT	         200	

#define OBJECT_TYPE_PORTAL	         50